[docker compose CI] adding meaningful error

diff --git a/.github/workflows/test_compose.yml b/.github/workflows/test_compose.yml
--- a/.github/workflows/test_compose.yml
+++ b/.github/workflows/test_compose.yml
@@ -17,7 +17,7 @@ jobs:
         run: docker exec $(docker ps -qf "name=ci_listener_1") sh -c "if pgrep gedit >/dev/null 2>&1; then pkill yarp; else touch /outcome/ci_listener_1.fail; fi"
 
       - name: Check if something failed
-        run: cd .ci && if [ -n "$(find . -name '*.fail')" ]; then echo "error"; exit 1; fi
+        run: cd .ci && if [ -n "$(find . -name '*.fail')" ]; then echo $(find . -name '*.fail'); exit 1; fi
 
       - name: Stop the stack
         run: cd .ci && docker-compose down
